routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route for authentication
Auth::routes();

// Route for frontend
Route::get('/','IndexController@index')->name('index');
Route::get('/gioi-thieu', 'IndexController@about')->name('gioi-thieu');
//Route::get('/khuyen-mai', 'IndexController@sale')->name('khuyen-mai');

Route::get('/dang-ky-kham', 'IndexController@registerMedicalApplication')->name('dang-ky-kham');
Route::post('/dang-ky-kham', 'IndexController@sendRegisterMedicalApplication');
Route::get('/dang-ky-thanh-vien', 'IndexController@registerMember')->name('dang-ky-thanh-vien');
Route::get('/dang-ky-thanh-vien', 'IndexController@registerMember')->name('dang-ky-thanh-vien');
Route::get('/thong-tin-benh-nhan', 'IndexController@personalInformation')->name('thong-tin-benh-nhan');

Route::get('/bac-sy/dang-ky', 'IndexController@registerDoctor')->name('dang-ky-bac-sy');
Route::post('/bac-sy/dang-ky', 'IndexController@sendRegisterDoctor');
Route::get('/bac-sy/quy-dinh', 'IndexController@doctorPolicy')->name('quy-dinh-bac-sy');
Route::get('/bac-sy/danh-sach', 'IndexController@doctorList')->name('danh-sach-bac-sy');
//Route::get('/bac-sy/thong-tin', 'IndexController@doctorInfomation')->name('thong-tin-bac-sy');

Route::get('/san-pham', 'IndexController@services')->name('san-pham');
Route::get('/dung-cu-y-te', 'IndexController@medicalInstruments')->name('dung-cu-y-te');
Route::get('/thuoc', 'IndexController@medical')->name('thuoc');

Route::get('/tin-tuc', 'IndexController@news')->name('tin-tuc');
Route::get('/cam-nang', 'IndexController@handBook')->name('hand-book');
Route::get('/tuyen-dung', 'IndexController@recruit')->name('recruit');
Route::get('/khuyen-mai', 'IndexController@sale')->name('sale');

Route::get('/lien-he', 'IndexController@contact')->name('contact');




// Route for backend
// All below route go with 'admin' prefix and need authentication
// All route name with add admin. prefix
Route::group([	'prefix' => 'admin',	'middleware' => 'auth', 'as' => 'admin.'	], function() {

	Route::get('/','AdminController@index')
	->name('index');

    Route::group([ 'middleware' => ['permission:manage-user']], function() {
		Route::resource('user',	'UserController');
    });

    Route::group(['middleware' => ['permission:manage-role']], function() {
        Route::resource('role', 'RoleController');
    });

    Route::group(['middleware' => ['role:admin']], function() {
        Route::get('permission/install','PermissionController@install')->name('permission.install');
        Route::post('permission/install','PermissionController@installPost')->name('permission.generate');
		Route::resource('permission',	'PermissionController');
    });

    Route::group(['middleware' => ['permission:manage-category']], function() {
        Route::resource('category', 'CategoryController');
    });

    Route::group(['middleware' => ['permission:manage-tag']], function() {
        Route::resource('tag', 'TagController');
    });

    Route::group(['middleware' => ['permission:manage-post']], function() {
        Route::resource('post', 'PostController');
    });

}); //End route group admin

Route::get('post/{slug}', 'IndexController@viewPost');

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Post extends Model
{
    use SoftDeletes;
    protected $dates = ['deleted_at'];
    protected $guarded = ['id', 'category'];

    public function category(){
    	return $this->belongsToMany('\App\Category','post_category','post_id','category_id');
    }

    public function hasCategory($category)
    {
        if ($this->category()->where('category_id',$category)->first()){
            return true;
        }
        return false;
    }

    public function tag(){
    	return $this->belongsToMany('\App\Category','post_tag','post_id','tag_id');
    }

    public function hasTag($category)
    {
        if ($this->category()->where('tag _id',$category)->first()){
            return true;
        }
        return false;
    }

    public function author(){
    	return $this->belongsTo('\App\User','author_id');
    }

    public function getUrl(){
        $base_url = Url('/');
        $prefix_url = 'post';
        $url = $base_url.'/'.$prefix_url.'/'.$this->slug.'';
        return $url;
    }

    public function getShortDec(){
        if (strlen($this->description) > 100){
            return substr($this->description, 0,strpos($this->description, ' ', 100)) . ' ...';
        } else {
        return $this->description;
        }
    }

    public function getEditUrl(){
        return route('edit-post',['id'=>$this->id]);
    }

}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Post;
use App\Category;
use Illuminate\Support\Facades\Input; 
use Auth;

class PostController extends Controller
{
	public function index() {
		$posts = Post::paginate();
		return view('admin.post.index', compact('posts'));
	}

	public function create() {
		$categories = Category::all();
		return view('admin.post.create', compact('categories'));
	}

	public function store(Request $request) {

		
		$slug = str_slug($request->input('title'));
		// Assign default slug
		Input::merge(['author_id' => Auth::user()->id]);
		if( !$request->input('slug')) {
			Input::merge(['slug' => $slug]);
		}
		// Check for duplicate slug
		$suffix = 1;
		while(Post::where('slug','=',$request->input('slug'))->first()){
			Input::merge(['slug' => $slug.'-'.$suffix++]);
		}
		// Add post from request		
		try {
			$post = Post::create($request->all());
			if($request->input('category')) {				
				foreach ($request->category as $x){
					$post->category()->attach($x);	
				}
			}

			\Session::flash('flash_message','Đã tạo bài viết '.$post->title .' thành công!');
			return redirect()->route('admin.post.index');
			return redirect()->route('admin.post.edit', ['id' => $post->id]);
		} catch (\Exception $e) {
			return $e;
		}
	}

	public function edit(Post $post) {
		
		//return Post::find($post)->title;
		$categories = Category::all();
		return view('admin.post.edit', compact('post', 'categories'));
	}

	public function update(Post $post, Request $request) {
		$post->category()->detach();
		$post->update($request->all());
		if($request->input('category')) {				
			foreach ($request->category as $x){
				$post->category()->attach($x);	
			}
		}
		return redirect()->route('admin.post.edit', ['id' => $post->id]);
	}

	public function destroy(Post $post) {
		Post::destroy($post->id);
		return redirect()->route('admin.post.index');
	}
    
}

resources/views/admin/post/create.blade.php
@extends('admin.layouts.apps')
@section('title')
Thêm bài viết
@endsection
@section('main')

<div class="col-md-12 col-sm-12 col-xs-12">
    @if($errors->any())
    <div class="alert alert-danger alert-dismissible fade in" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span>
        </button>
        <strong>Lỗi!</strong>
        <ul>
            @foreach ($errors->all() as $message)
            <li>{{$message}}</li>
            @endforeach
        </ul>

    </div>
    @endif
    <div class="x_panel">
        <div class="x_title">
            <h2>Thêm bài viết</h2>

            <div class="clearfix"></div>
        </div>
        <div class="x_content">
            <br />
            <form action="{{ route('admin.post.store') }}" id="add_post"  class="form-horizontal form-label-left" method="POST">
                {{ csrf_field() }}

                <div class="input-group">
                   <span class="input-group-btn">
                        <a id="lfm" data-input="thumbnail" data-preview="holder" class="btn btn-primary">
                            <i class="fa fa-picture-o"></i> Choose
                        </a>
                    </span>
                    <input id="thumbnail" class="form-control" type="text" name="avatar">
                </div>
                <div class="form-group">
                    <img id="holder" style="margin-top:15px;max-height:100px;">
                </div>


                <div class="form-group ">
                    <label>Tiêu đề bài viết<span class="required">*</span>
                    </label>

                        <input name="title" type="text" class="form-control col-md-7 col-xs-12 {{ ($errors->has('title'))?'parsley-error':'' }}" required="" >
                        @if ($errors->has('title'))
                        <ul class="parsley-errors-list">
                            @foreach ($errors->get('title') as $message)
                            <li>{{$message}}</li>
                            @endforeach
                        </ul>
                        @endif


                </div>
                <div class="form-group">
                    <label>Nội dung</label>
                    <textarea id="my-editor" name="content" class="form-control">{!! old('content', '') !!}</textarea>
                </div>

               <div class="form-group">
                   <label>Seo title</label>
                   <input type="text" name="seo_title" class="form-control">
               </div>

               <div class="form-group">
                   <label>Seo description</label>
                   <input type="text" name="seo_description" class="form-control">
               </div>

               <div class="form-group">
                    <label>Danh mục</label>
                    @foreach($categories as $category)
                    <div class="checkbox">
                        <label><input type="checkbox" name="category[]" value="{{ $category->id }}">{{ $category->name }}</label>
                    </div>
                    @endforeach
               </div>

               <div class="form-group">
                    <label for="">Đăng nháp</label>
                    <div class="checkbox">
                        <label><input type="checkbox" name="deleted_at" value="{{ date("Y-m-d H:i:s") }}">Đăng nháp</label>
                    </div>
               </div>

                <div class="ln_solid"></div>
                <div class="form-group">
                        <a href=".">
                            <button class="btn btn-default" type="button">Quay lại</button>
                        </a>
                        <button class="btn btn-default" type="reset">Reset</button>
                        <button type="submit" class="btn btn-success">Thêm</button>

                </div>

            </form>
        </div>
    </div>
</div>

@endsection
@section('script')
<script src="/vendor/unisharp/laravel-ckeditor/ckeditor.js"></script>
<script src="/vendor/laravel-filemanager/js/lfm.js"></script>
<script>
  var options = {
    filebrowserImageBrowseUrl: '/laravel-filemanager?type=Images',
    filebrowserImageUploadUrl: '/laravel-filemanager/upload?type=Images&_token=',
    filebrowserBrowseUrl: '/laravel-filemanager?type=Files',
    filebrowserUploadUrl: '/laravel-filemanager/upload?type=Files&_token=',
  };

</script>

<script>
    $ckedit = CKEDITOR.replace('my-editor', options);
    $ckedit.config.extraPlugins = 'format';
    $('#lfm').filemanager('image');
    $('#lfm').filemanager('file');

</script>




@endsection

resources/views/admin/post/edit.blade.php
@extends('admin.layouts.apps')
@section('title')
Thêm bài viết
@endsection
@section('main')

<div class="col-md-12 col-sm-12 col-xs-12">
    @if($errors->any())
    <div class="alert alert-danger alert-dismissible fade in" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span>
        </button>
        <strong>Lỗi!</strong>
        <ul>
            @foreach ($errors->all() as $message)
            <li>{{$message}}</li>
            @endforeach
        </ul>

    </div>
    @endif
    <div class="x_panel">
        <div class="x_title">
            <h2>Sửa bài viết</h2>

            <div class="clearfix"></div>
        </div>
        <div class="x_content">
            <br />
            <form action="{{ route('admin.post.update',['post' => $post->id ]) }}" id="add_post"  class="form-horizontal form-label-left" method="POST">
                {{ csrf_field() }}
                {{ method_field('PATCH') }}

                <div class="input-group">
                   <span class="input-group-btn">
                        <a id="lfm" data-input="thumbnail" data-preview="holder" class="btn btn-primary">
                            <i class="fa fa-picture-o"></i> Choose
                        </a>
                    </span>
                    <input id="thumbnail" class="form-control" type="text" name="avatar" value="{{ $post->avatar }}">
                </div>
                <div class="form-group">
                    <img id="holder" style="margin-top:15px;max-height:100px;" src="{{ $post->avatar }}">
                </div>

                <div class="form-group ">
                    <label>Tiêu đề bài viết<span class="required">*</span>
                    </label>

                        <input name="title" type="text" class="form-control col-md-7 col-xs-12 {{ ($errors->has('title'))?'parsley-error':'' }}" required="" value="{{ $post->title }}">
                        @if ($errors->has('title'))
                        <ul class="parsley-errors-list">
                            @foreach ($errors->get('title') as $message)
                            <li>{{$message}}</li>
                            @endforeach
                        </ul>
                        @endif


                </div>
                <div class="form-group">
                    <label>Nội dung</label>
                    <textarea id="my-editor" name="content" class="form-control">{!! $post->content !!}</textarea>
                </div>

               <div class="form-group">
                   <label>Seo title</label>
                   <input type="text" name="seo_title" class="form-control" value="{{ $post->seo_title }}">
               </div>

               <div class="form-group">
                   <label>Seo description</label>
                   <input type="text" name="seo_description" class="form-control" value="{{ $post->seo_description }}">
               </div>

               <div class="form-group">
                    <label>Danh mục</label>
                    @foreach($categories as $category)
                    <div class="checkbox">
                        <label><input type="checkbox"
                            name="category[]"
                            value="{{ $category->id }}"
                            {{ $post->hasCategory($category->id)?'checked':'' }}>
                            {{ $category->name }}
                        </label>
                    </div>
                    @endforeach
               </div>

                <div class="ln_solid"></div>
                <div class="form-group">
                        <a href=".">
                            <button class="btn btn-default" type="button">Quay lại</button>
                        </a>
                        <button class="btn btn-default" type="reset">Reset</button>
                        <button type="submit" class="btn btn-success">Sửa</button>

                </div>

            </form>
        </div>
    </div>
</div>

@endsection
@section('script')
<script src="/vendor/unisharp/laravel-ckeditor/ckeditor.js"></script>
<script src="/vendor/laravel-filemanager/js/lfm.js"></script>
<script>
  var options = {
    filebrowserImageBrowseUrl: '/laravel-filemanager?type=Images',
    filebrowserImageUploadUrl: '/laravel-filemanager/upload?type=Images&_token=',
    filebrowserBrowseUrl: '/laravel-filemanager?type=Files',
    filebrowserUploadUrl: '/laravel-filemanager/upload?type=Files&_token='
  };
</script>
<script>
    $ckedit = CKEDITOR.replace('my-editor', options);
    $ckedit.config.extraPlugins = 'format';
    $('#lfm').filemanager('image');
    $('#lfm').filemanager('file');

</script>


@endsection

resources/views/admin/post/index.blade.php
@extends('admin.layouts.apps')
@section('title')
Danh sách thành viên
@endsection
@section('main')
<div class="col-md-12 col-sm-12 col-xs-12">

	@if(Session::has('flash_message'))
	<div class="alert alert-success"><em> {!! session('flash_message') !!}</em></div>
	@endif
	<div class="x_panel">
		<div class="x_title">
			<h2>Danh sách bài viết</h2>
			<div class="clearfix"></div>
		</div>

		<div class="x_content">
			<div class="table-responsive">
			<?php echo $posts->render(); ?>
				<table class="table table-striped jambo_table bulk_action">
					<thead>
						<tr class="headings">
							<td>ID</td>
							<td>Tên bài viết</td>
							<td>Sửa</td>
							<td>Xóa</td>
						</tr>
					</thead>
					<tbody>
						@foreach($posts as $post)
						<tr>
							<td>{{ $post->id }}</td>
							<td><a href="{{ $post->getUrl() }}" target="_blank">{{ $post->title }}</a></td>

							<!-- <td>
								<a href="{{ route('admin.post.show',['post' => $post]) }}">Xem</a>
							</td> -->
							<td>
								<a href="{{ route('admin.post.edit',['post' => $post]) }}">Sửa</a>
							</td>
							<td>
								<a href="#" class="remove_link text-danger" data-toggle="modal" data-target="#destroy-post" data-value="{{ route('admin.post.destroy',['post' => $post]) }}">Xóa</a>
							</td>
						</tr>
						@endforeach
					</tbody>
				</table>
				<?php echo $posts->render(); ?>
			</div>
		</div>
	</div>
</div>
<div id="destroy-post" class="modal fade bs-example-modal-lg" tabindex="-1" post="dialog" aria-hidden="true">
	<div class="modal-dialog modal-lg">
		<div class="modal-content">

			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span>
				</button>
				<h4 class="modal-title">Xóa bài viết</h4>
			</div>
			<div class="modal-body">
				<p>Bạn có chắc chắn xóa bài viết này chứ?</p>
			</div>
			<div class="modal-footer">
				<button id="close_button" type="button" class="btn btn-default" data-dismiss="modal">Close</button>
				<form id="destroy_form" style="display:inline;" action="" method="POST">
					{{ csrf_field() }}
					{{ method_field('DELETE') }}

					<button type="submit" class="btn btn-danger">Xóa</button>
				</form>
			</div>

		</div>
	</div>
</div>

@endsection
@section('script')
<script>
	$(document).ready(function(){
		$(".remove_link").click(function(){
			$('#destroy_form').attr("action",$(this).attr("data-value"));

		});
		$("#close_button").click(function(){
			$('#destroy_form').attr("action",'');
		});
	});
</script>
@endsection

resources/views/admin/post/install.blade.php
@extends('admin.layouts.apps')
@section('title')
Danh sách thành viên
@endsection
@section('main')
	<p>Sau đây là danh sách các quyền sẽ được cài đặt</p>
	<ul>
		@foreach($permissions as $permission)
			<li>
				{{ $permission }}
			</li>
		@endforeach
	</ul>
	<p class="text-danger">Việc cài đặt này có thể làm mất hết danh sách quyền!</p>
	<form action="{{route('admin.permission.install')}}" method="post">
		{{ csrf_field() }}
		<button type="submit">Cài đặt</button>		
	</form>
@endsection
@section('script')

@endsection

resources/views/admin/post/show.blade.php
@extends('admin.layouts.apps')
@section('main')

<p>ID: {{ $permission->id }}</p>
<p>Name : {{ $permission->id }} </p>
<p>Tên hiển thị: {{ $permission->display_name}} </p>
<p>Miêu tả chi tiết: {{ $permission->description }} </p>

@endsection