routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route for authentication
Auth::routes();

// Route for frontend
Route::get('/','IndexController@index')->name('index');
Route::get('/gioi-thieu', 'IndexController@about')->name('gioi-thieu');
//Route::get('/khuyen-mai', 'IndexController@sale')->name('khuyen-mai');

Route::get('/dang-ky-kham', 'IndexController@registerMedicalApplication')->name('dang-ky-kham');
Route::post('/dang-ky-kham', 'IndexController@sendRegisterMedicalApplication');
Route::get('/dang-ky-thanh-vien', 'IndexController@registerMember')->name('dang-ky-thanh-vien');
Route::get('/dang-ky-thanh-vien', 'IndexController@registerMember')->name('dang-ky-thanh-vien');
Route::get('/thong-tin-benh-nhan', 'IndexController@personalInformation')->name('thong-tin-benh-nhan');

Route::get('/bac-sy/dang-ky', 'IndexController@registerDoctor')->name('dang-ky-bac-sy');
Route::post('/bac-sy/dang-ky', 'IndexController@sendRegisterDoctor');
Route::get('/bac-sy/quy-dinh', 'IndexController@doctorPolicy')->name('quy-dinh-bac-sy');
Route::get('/bac-sy/danh-sach', 'IndexController@doctorList')->name('danh-sach-bac-sy');
//Route::get('/bac-sy/thong-tin', 'IndexController@doctorInfomation')->name('thong-tin-bac-sy');

Route::get('/san-pham', 'IndexController@services')->name('san-pham');
Route::get('/dung-cu-y-te', 'IndexController@medicalInstruments')->name('dung-cu-y-te');
Route::get('/thuoc', 'IndexController@medical')->name('thuoc');

Route::get('/tin-tuc', 'IndexController@news')->name('tin-tuc');
Route::get('/cam-nang', 'IndexController@handBook')->name('hand-book');
Route::get('/tuyen-dung', 'IndexController@recruit')->name('recruit');
Route::get('/khuyen-mai', 'IndexController@sale')->name('sale');

Route::get('/lien-he', 'IndexController@contact')->name('contact');




// Route for backend
// All below route go with 'admin' prefix and need authentication
// All route name with add admin. prefix
Route::group([	'prefix' => 'admin',	'middleware' => 'auth', 'as' => 'admin.'	], function() {

	Route::get('/','AdminController@index')
	->name('index');

    Route::group([ 'middleware' => ['permission:manage-user']], function() {
		Route::resource('user',	'UserController');
    });

    Route::group(['middleware' => ['permission:manage-role']], function() {
        Route::resource('role', 'RoleController');
    });

    Route::group(['middleware' => ['role:admin']], function() {
        Route::get('permission/install','PermissionController@install')->name('permission.install');
        Route::post('permission/install','PermissionController@installPost')->name('permission.generate');
		Route::resource('permission',	'PermissionController');
    });

    Route::group(['middleware' => ['permission:manage-category']], function() {
        Route::resource('category', 'CategoryController');
    });

    Route::group(['middleware' => ['permission:manage-tag']], function() {
        Route::resource('tag', 'TagController');
    });

    Route::group(['middleware' => ['permission:manage-post']], function() {
        Route::resource('post', 'PostController');
    });

}); //End route group admin

Route::get('post/{slug}', 'IndexController@viewPost');

resources/views/admin/layouts/apps.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <!-- Meta, title, CSS, favicons, etc. -->
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title>@yield('title')</title>

  <!-- Bootstrap -->
  <!-- <link href="{{ asset('css/app.css') }}" rel="stylesheet"> -->
  <link href="{{ asset('backend/vendors/bootstrap/dist/css/bootstrap.min.css') }}" rel="stylesheet">
  <!-- Font Awesome -->
  <link href="{{ asset('backend/vendors/font-awesome/css/font-awesome.min.css') }}" rel="stylesheet">
  <!-- NProgress -->
  <link href="{{ asset('backend/vendors/nprogress/nprogress.css') }}" rel="stylesheet">
  <!-- iCheck -->
  <link href="{{ asset('backend/vendors/iCheck/skins/flat/green.css') }}" rel="stylesheet">

  <!-- bootstrap-progressbar -->
  <link href="{{ asset('backend/vendors/bootstrap-progressbar/css/bootstrap-progressbar-3.3.4.min.css') }}" rel="stylesheet">
  <!-- JQVMap -->
  <link href="{{ asset('backend/vendors/jqvmap/dist/jqvmap.min.css') }}" rel="stylesheet"/>
  <!-- bootstrap-daterangepicker -->
  <link href="{{ asset('backend/vendors/bootstrap-daterangepicker/daterangepicker.css') }}" rel="stylesheet">
  <!-- Switchery -->
  <link href="{{ asset('backend/vendors/switchery/dist/switchery.min.css') }}" rel="stylesheet">
  <!-- Custom Theme Style -->
  <link href="{{ asset('backend/build/css/custom.min.css') }}" rel="stylesheet">

  <!-- Scripts -->
  <script>
    window.Laravel = {!! json_encode([
      'csrfToken' => csrf_token(),
      ]) !!};
  </script>

  </head>

  <body class="nav-md">
    <div class="container body">
      <div class="main_container">
        <div class="col-md-3 left_col">
          <div class="left_col scroll-view">
            <div class="navbar nav_title" style="border: 0;">
              <a href="{{ url('/')}}" class="site_title" target="_blank"><i class="fa fa-connectdevelop"></i> <span>Y Đạo Việt</span></a>
            </div>

            <div class="clearfix"></div>

            <!-- menu profile quick info -->
            <div class="profile clearfix">
              <div class="profile_pic">
                <img src="{{asset('images/logo.png')}}" alt="..." class="img-circle profile_img">
              </div>
              <div class="profile_info">
                <span>Welcome,</span>
                <h2>{{ Auth::user()->name }}</h2>
              </div>
            </div>
            <!-- /menu profile quick info -->

            <br />

            <!-- sidebar menu -->
            @include('admin.layouts.menu')
            <!-- /sidebar menu -->

          </div>
        </div>

        <!-- top navigation -->
        <div class="top_nav">
          <div class="nav_menu">
            <nav>
              <div class="nav toggle">
                <a id="menu_toggle"><i class="fa fa-bars"></i></a>
              </div>

              <ul class="nav navbar-nav navbar-right">
                <li class="">
                  <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                    <img src="{{asset('images/logo.png')}}" alt="">{{ Auth::user()->name }}
                    <span class=" fa fa-angle-down"></span>
                  </a>
                  <ul class="dropdown-menu dropdown-usermenu pull-right">
                    <li>
                        <a href="{{ route('logout') }}"
                            onclick="event.preventDefault();
                                     document.getElementById('logout-form').submit();">
                            Logout
                        </a>

                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                            {{ csrf_field() }}
                        </form>
                    </li>
                  </ul>
                </li>


              </ul>
            </nav>
          </div>
        </div>
        <!-- /top navigation -->

        <!-- page content -->
        <div class="right_col" role="main">
          @yield('main')
        </div>
        <!-- /page content -->

        <!-- footer content -->
        <footer>
          <div class="pull-right">
            Laravel CMS by <a href="https://www.facebook.com/quanbka">Quân Lê</a>
          </div>
          <div class="clearfix"></div>
        </footer>
        <!-- /footer content -->
      </div>
    </div>

    <!-- jQuery -->
    <script src="{{ asset('backend/vendors/jquery/dist/jquery.min.js') }}"></script>
    <!-- Bootstrap -->
    <script src="{{ asset('backend/vendors/bootstrap/dist/js/bootstrap.min.js') }}"></script>
    <!-- FastClick -->
    <script src="{{ asset('backend/vendors/fastclick/lib/fastclick.js') }}"></script>
    <!-- NProgress -->
    <script src="{{ asset('backend/vendors/nprogress/nprogress.js') }}"></script>
    <!-- Chart.js -->
    <script src="{{ asset('backend/vendors/Chart.js/dist/Chart.min.js') }}"></script>
    <!-- gauge.js -->
    <script src="{{ asset('backend/vendors/gauge.js/dist/gauge.min.js') }}"></script>
    <!-- bootstrap-progressbar -->
    <script src="{{ asset('backend/vendors/bootstrap-progressbar/bootstrap-progressbar.min.js') }}"></script>
    <!-- iCheck -->
    <script src="{{ asset('backend/vendors/iCheck/icheck.min.js') }}"></script>
    <!-- Skycons -->
    <script src="{{ asset('backend/vendors/skycons/skycons.js') }}"></script>
    <!-- Flot -->
    <script src="{{ asset('backend/vendors/Flot/jquery.flot.js') }}"></script>
    <script src="{{ asset('backend/vendors/Flot/jquery.flot.pie.js') }}"></script>
    <script src="{{ asset('backend/vendors/Flot/jquery.flot.time.js') }}"></script>
    <script src="{{ asset('backend/vendors/Flot/jquery.flot.stack.js') }}"></script>
    <script src="{{ asset('backend/vendors/Flot/jquery.flot.resize.js') }}"></script>
    <!-- Flot plugins -->
    <script src="{{ asset('backend/vendors/flot.orderbars/js/jquery.flot.orderBars.js') }}"></script>
    <script src="{{ asset('backend/vendors/flot-spline/js/jquery.flot.spline.min.js') }}"></script>
    <script src="{{ asset('backend/vendors/flot.curvedlines/curvedLines.js') }}"></script>
    <!-- DateJS -->
    <script src="{{ asset('backend/vendors/DateJS/build/date.js') }}"></script>
    <!-- JQVMap -->
    <script src="{{ asset('backend/vendors/jqvmap/dist/jquery.vmap.js') }}"></script>
    <script src="{{ asset('backend/vendors/jqvmap/dist/maps/jquery.vmap.world.js') }}"></script>
    <script src="{{ asset('backend/vendors/jqvmap/examples/js/jquery.vmap.sampledata.js') }}"></script>
    <!-- bootstrap-daterangepicker -->
    <script src="{{ asset('backend/vendors/moment/min/moment.min.js') }}"></script>
    <script src="{{ asset('backend/vendors/bootstrap-daterangepicker/daterangepicker.js') }}"></script>
    <!-- Switchery -->
    <script src="{{ asset('backend/vendors/switchery/dist/switchery.min.js') }}"></script>
    <!-- Custom Theme Scripts -->
    <script src="{{ asset('backend/build/js/custom.min.js') }}"></script>
    @yield('script')


  </body>
  </html>

resources/views/admin/layouts/menu.blade.php
<div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
              <div class="menu_section">
                <h3>Quản lý nội dung</h3>
                <ul class="nav side-menu">
                  <li><a href="{{ route('admin.index') }}"><i class="fa fa-home"></i> Bảng tin </a>
                  </li>
                  <li><a href="#"><i class="fa fa-edit"></i> Bài viết <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                      <li><a href="{{ route('admin.post.create') }}">Viết bài mới</a></li>
                      <li><a href="{{ route('admin.post.index') }}">Danh sách bài viết</a></li>
                      <li><a href="{{ route('admin.category.index') }}">Danh mục</a></li>
                      <li><a href="{{ route('admin.tag.index') }}">Thẻ</a></li>
                    </ul>
                  </li>                  
                  <li><a><i class="fa fa-files-o"></i> Trang <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                      <li><a href="#">Tạo trang mới</a></li>
                      <li><a href="#">Danh sách trang</a></li>
                    </ul>
                  </li>                  
                </ul>
              </div>
              <div class="menu_section">
                <h3>Quản lý người dùng</h3>
                <ul class="nav side-menu">
                  <li><a><i class="fa fa-envelope"></i> Liên hệ </a>
                  </li>

                  <li><a><i class="fa fa-user"></i> Thành viên <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                      <li><a href="{{ route('admin.user.create') }}">Thêm thành viên</a></li>
                      <li><a href="{{ route('admin.user.index') }}">Danh sách thành viên</a></li>
                    </ul>
                  </li>

                  <li><a><i class="fa fa-users"></i> Vai <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                      <li><a href="{{ route('admin.role.create') }}">Thêm vai</a></li>
                      <li><a href="{{ route('admin.role.index') }}">Danh sách vai trò</a></li>
                    </ul>
                  </li>

                  <li><a><i class="fa fa-users"></i> Phân quyền <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                      <li><a href="{{ route('admin.permission.create') }}">Thêm quyền</a></li>
                      <li><a href="{{ route('admin.permission.index') }}">Danh sách quyền</a></li>
                      <li><a href="{{ route('admin.permission.install') }}">Khởi tạo quyền <span class="label label-danger pull-right">Nguy hiểm</span></a></li>
                    </ul>
                  </li>

                </ul>
              </div>

              <div class="menu_section">
                <h3>Cài đặt</h3>
                <ul class="nav side-menu">
                  <li><a><i class="fa fa-cogs"></i> Cài đặt <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                      <li><a href="#">Cấu hình website</a></li>
                      <li><a href="#">Chèn mã html</a></li>
                    </ul>
                  </li>
                </ul>
              </div>

              <!-- <div class="menu_section">
                <h3>Quản lý căn hộ</h3>
                <ul class="nav side-menu">
                  <li><a><i class="fa fa-home"></i> Căn hộ <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                      <li><a href="#">Thêm căn hộ</a></li>
                      <li><a href="#">Danh sách căn hộ</a></li>
                    </ul>
                  </li>
                  <li><a><i class="fa fa-building"></i> Dự án <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
                      <li><a href="#">Thêm dự án</a></li>
                      <li><a href="#">Danh sách dự án</a></li>
                    </ul>
                  </li>
                </ul>
              </div> -->

            </div>