routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route for authentication
Auth::routes();

// Route for frontend
Route::get('/','IndexController@index')->name('index');
Route::get('/gioi-thieu', 'IndexController@about')->name('gioi-thieu');
//Route::get('/khuyen-mai', 'IndexController@sale')->name('khuyen-mai');

Route::get('/dang-ky-kham', 'IndexController@registerMedicalApplication')->name('dang-ky-kham');
Route::post('/dang-ky-kham', 'IndexController@sendRegisterMedicalApplication');
Route::get('/dang-ky-thanh-vien', 'IndexController@registerMember')->name('dang-ky-thanh-vien');
Route::get('/dang-ky-thanh-vien', 'IndexController@registerMember')->name('dang-ky-thanh-vien');
Route::get('/thong-tin-benh-nhan', 'IndexController@personalInformation')->name('thong-tin-benh-nhan');

Route::get('/bac-sy/dang-ky', 'IndexController@registerDoctor')->name('dang-ky-bac-sy');
Route::post('/bac-sy/dang-ky', 'IndexController@sendRegisterDoctor');
Route::get('/bac-sy/quy-dinh', 'IndexController@doctorPolicy')->name('quy-dinh-bac-sy');
Route::get('/bac-sy/danh-sach', 'IndexController@doctorList')->name('danh-sach-bac-sy');
//Route::get('/bac-sy/thong-tin', 'IndexController@doctorInfomation')->name('thong-tin-bac-sy');

Route::get('/san-pham', 'IndexController@services')->name('san-pham');
Route::get('/dung-cu-y-te', 'IndexController@medicalInstruments')->name('dung-cu-y-te');
Route::get('/thuoc', 'IndexController@medical')->name('thuoc');

Route::get('/tin-tuc', 'IndexController@news')->name('tin-tuc');
Route::get('/cam-nang', 'IndexController@handBook')->name('hand-book');
Route::get('/tuyen-dung', 'IndexController@recruit')->name('recruit');
Route::get('/khuyen-mai', 'IndexController@sale')->name('sale');

Route::get('/lien-he', 'IndexController@contact')->name('contact');




// Route for backend
// All below route go with 'admin' prefix and need authentication
// All route name with add admin. prefix
Route::group([	'prefix' => 'admin',	'middleware' => 'auth', 'as' => 'admin.'	], function() {

	Route::get('/','AdminController@index')
	->name('index');

    Route::group([ 'middleware' => ['permission:manage-user']], function() {
		Route::resource('user',	'UserController');
    });

    Route::group(['middleware' => ['permission:manage-role']], function() {
        Route::resource('role', 'RoleController');
    });

    Route::group(['middleware' => ['role:admin']], function() {
        Route::get('permission/install','PermissionController@install')->name('permission.install');
        Route::post('permission/install','PermissionController@installPost')->name('permission.generate');
		Route::resource('permission',	'PermissionController');
    });

    Route::group(['middleware' => ['permission:manage-category']], function() {
        Route::resource('category', 'CategoryController');
    });

    Route::group(['middleware' => ['permission:manage-tag']], function() {
        Route::resource('tag', 'TagController');
    });

    Route::group(['middleware' => ['permission:manage-post']], function() {
        Route::resource('post', 'PostController');
    });

}); //End route group admin

Route::get('post/{slug}', 'IndexController@viewPost');

app/Permission.php
<?php 

namespace App;

use Zizaco\Entrust\EntrustPermission;

class Permission extends EntrustPermission
{
	protected $guarded = ['id'];
	protected $fillable = ['name','display_name','description'];
}

app/Http/Controllers/PermissionController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Permission;
use App\Role;
use Redirect;
use Route;
use Illuminate\Support\Facades\DB;
use App\Http\Requests\PermissionRequest;

class PermissionController extends Controller
{
    //Return index, show list of permissions
    //Method get
    public function index(){
    	$permissions = Permission::paginate(20);

    	return view('admin.permission.index',compact('permissions'));
    }

    //Show permission details
    //Method get
    public function show($permission){
        $permission = Permission::findOrFail($permission);
    	return view('admin.permission.show',compact('permission'));
    }

	//Return create permission page
    //Method get
    public function create(){
    	$roles = Role::all();
    	return view('admin.permission.create',compact('roles'));
    }

    //Store a permission to database
    //Method post
    public function store(PermissionRequest $request){
        try {
            $permission =  Permission::create($request->all());
            \Session::flash('flash_message','Đã tạo quyền '.$permission->name .' thành công!');
            return redirect()->route('admin.permission.index');
        } catch (\Illuminate\Database\QueryException $e) {
            if($e->errorInfo[1]==1062){
                return Redirect::back()->withErrors('Dữ liệu nhập trùng với dữ liệu trong cơ sở diệu');
            }
            return Redirect::back()->withErrors($e->errorInfo[2]);
        }

    }

    //Show permission edit page
    //Method get
    public function edit($permission){
        $permission = Permission::findOrFail($permission);
    	return view('admin.permission.edit',compact('permission'));
    }

    //Update a permission
    //Method put patch
    public function update($permission, PermissionRequest $request){
        $permission = Permission::findOrFail($permission);
        $permission->update($request->all());
        \Session::flash('flash_message','Đã sửa quyền thành công!');
        return Redirect::back();
    }

    //Remove a permission
    //Method delete
    public function destroy($permission){
        $permission = Permission::findOrFail($permission);
        $permission->delete();
        \Session::flash('flash_message','Đã xóa quyền thành côngs!');
        return redirect()->route('admin.permission.index');

    }

    public function install(){
        return 0;
        $routes = Route::getRoutes(); //Khoi tao route collection
        $middlewares = array('admin'); //Khoi tao danh sach middleware

        foreach ($routes as $value) {
            if(is_array($value->action['middleware'])){ //Kiem tra neu middleware la array
                $middlewares = array_merge($middlewares,$value->action['middleware']); //Chen middleware array vao danh sach middleware
            }
        }

        $middlewares = array_unique($middlewares); //Loc cac ket qua trung lap
        $permissions = array();

        foreach($middlewares as $value){

            if (strpos($value,'permission:')===0){ //Kiem tra neu co permission trong middleware
                $value = substr($value,11);
                array_push($permissions,$value); //Dua permission vao danh sach
            }
        }

        //print_r($permissions); //In ra danh sach
        return view('admin.permission.install',compact('permissions'));
    }

    public function installPost(){
        return 0;
        $routes = Route::getRoutes(); //Khoi tao route collection
        $middlewares = array('admin'); //Khoi tao danh sach middleware

        foreach ($routes as $value) {
            if(is_array($value->action['middleware'])){ //Kiem tra neu middleware la array
                $middlewares = array_merge($middlewares,$value->action['middleware']); //Chen middleware array vao danh sach middleware
            }
        }

        $middlewares = array_unique($middlewares); //Loc cac ket qua trung lap
        $permissions = array();

        foreach($middlewares as $value){

            if (strpos($value,'permission:')===0){ //Kiem tra neu co permission trong middleware
                $value = substr($value,11);
                array_push($permissions,$value); //Dua permission vao danh sach
            }
        }

        DB::table('permission_role')->truncate();
        DB::table('permissions')->delete();

        foreach($permissions as $permission){
        $permission = Permission::create([
            'name' => $permission,
           ]);
        $role_admin = Role::where('name','admin')->first();
        $role_admin->attachPermissions(array(
            $permission
            ));
        }

        \Session::flash('flash_message','Đã khởi tạo quyền thành công!');
        return redirect()->route('admin.permission.index');
    }
}

resources/views/admin/permission/create.blade.php
@extends('admin.layouts.apps')
@section('title')
Thêm quyền
@endsection
@section('main')    

<div class="col-md-12 col-sm-12 col-xs-12">
    @if($errors->any())
    <div class="alert alert-danger alert-dismissible fade in" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span>
        </button>
        <strong>Lỗi!</strong> 
        <ul>
            @foreach ($errors->all() as $message) 
            <li>{{$message}}</li>
            @endforeach
        </ul>

    </div>
    @endif
    <div class="x_panel">
        <div class="x_title">
            <h2>Thêm quyền</h2>

            <div class="clearfix"></div>
        </div>
        <div class="x_content">
            <br />
            <form action="{{ route('admin.permission.store') }}" id="add_permission"  class="form-horizontal form-label-left" method="POST">
                {{ csrf_field() }}

                <div class="form-group ">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">Tên quyền <span class="required">*</span>
                    </label>
                    <div class="col-md-6 col-sm-9 col-xs-12">
                        <input name="name" type="text" class="form-control col-md-7 col-xs-12 {{ ($errors->has('name'))?'parsley-error':'' }}" required="" >
                        @if ($errors->has('name'))
                        <ul class="parsley-errors-list">
                            @foreach ($errors->get('name') as $message) 
                            <li>{{$message}}</li>
                            @endforeach
                        </ul>
                        @endif
                    </div>
                    
                </div>

                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">Tên hiển thị quyền
                    </label>
                    <div class="col-md-6 col-sm-9 col-xs-12">
                        <input name="display_name" type="text" class="form-control col-md-7 col-xs-12 {{ ($errors->has('display_name'))?'parsley-error':'' }}">
                        @if ($errors->has('display_name'))
                        <ul class="parsley-errors-list">
                            @foreach ($errors->get('name') as $message) 
                            <li>{{$message}}</li>
                            @endforeach
                        </ul>
                        @endif
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">Miêu tả
                    </label>
                    <div class="col-md-6 col-sm-9 col-xs-12">
                        <input name="description" type="text"  class="form-control col-md-7 col-xs-12">
                    </div>
                </div>

                <div class="ln_solid"></div>
                <div class="form-group">
                    <div class="col-md-6 col-sm-9 col-xs-12 col-md-offset-3 col-sm-offset-3">
                        <a href=".">
                            <button class="btn btn-default" type="button">Quay lại</button>
                        </a>
                        <button class="btn btn-default" type="reset">Reset</button>
                        <button type="submit" class="btn btn-success">Thêm</button>
                    </div>
                </div>

            </form>
        </div>
    </div>
</div>

@endsection
@section('script')

@endsection

resources/views/admin/permission/edit.blade.php
@extends('admin.layouts.apps')
@section('title')
Sửa quyền
@endsection
@section('main')    

<div class="col-md-12 col-sm-12 col-xs-12">
    @if(Session::has('flash_message'))
        <div class="alert alert-success"><em> {!! session('flash_message') !!}</em></div>
    @endif
    @if($errors->any())
    <div class="alert alert-danger alert-dismissible fade in" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span>
        </button>
        <strong>Lỗi!</strong> 

        <ul>
            @foreach ($errors->all() as $message) 
            <li>{{$message}}</li>
            @endforeach
        </ul>

    </div>
    @endif
    <div class="x_panel">
        <div class="x_title">
            <h2>Sửa quyền</h2>

            <div class="clearfix"></div>
        </div>
        <div class="x_content">
            <br />
            <form action="{{ route('admin.permission.update',['permission' => $permission]) }}" id="add_permission" data-parsley-validate class="form-horizontal form-label-left" method="POST">

                {{ csrf_field() }}
                {{ method_field('PATCH') }}

                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">Tên quyền <span class="required">
                    </span>
                    </label>
                    <div class="col-md-6 col-sm-9 col-xs-12">
                        <input name="name" type="text" disabled class="form-control col-md-7 col-xs-12" value="{{$permission->name}}">
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">Tên hiển thị quyền
                    </label>
                    <div class="col-md-6 col-sm-9 col-xs-12">
                        <input name="display_name" type="text" class="form-control col-md-7 col-xs-12" value="{{$permission->display_name}}">
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">Miêu tả
                    </label>
                    <div class="col-md-6 col-sm-9 col-xs-12">
                        <input name="description" type="text"  class="form-control col-md-7 col-xs-12" value="{{$permission->description}}">
                    </div>
                </div>

                <div class="ln_solid"></div>
                <div class="form-group">
                    <div class="col-md-6 col-sm-9 col-xs-12 col-md-offset-3 col-sm-offset-3">
                        <a href="..">
                            <button class="btn btn-default" type="button">Quay lại</button>
                        </a>
                        <button class="btn btn-default" type="reset">Reset</button>

                        <button type="submit" class="btn btn-success">Cập nhật</button>
                    </div>
                </div>

            </form>
        </div>
    </div>
</div>

@endsection
@section('script')
<!-- Parsley -->
<script src="{{ asset('backend/vendors/parsleyjs/dist/parsley.min.js') }}"></script>
@endsection

resources/views/admin/permission/index.blade.php
@extends('admin.layouts.apps')
@section('title')
Danh sách thành viên
@endsection
@section('main')
<div class="col-md-12 col-sm-12 col-xs-12">

	@if(Session::has('flash_message'))
	<div class="alert alert-success"><em> {!! session('flash_message') !!}</em></div>
	@endif
	<div class="x_panel">
		<div class="x_title">
			<h2>Danh sách quyền</h2>                    
			<div class="clearfix"></div>
		</div>

		<div class="x_content">
			<div class="table-responsive">
			<?php echo $permissions->render(); ?>
				<table class="table table-striped jambo_table bulk_action">
					<thead>
						<tr class="headings">
							<td>ID</td>
							<td>Tên</td>
							<td>Tên hiển thị</td>
							<td>Miêu tả</td>
							<!-- <td>Xem</td> -->
							<td>Sửa</td>
							<td>Xóa</td>
						</tr>
					</thead>
					<tbody>
						@foreach($permissions as $permission)
						<tr>
							<td>{{ $permission->id }}</td>
							<td>{{ $permission->name }}</td>
							<td>{{ $permission->display_name }}</td>
							<td>{{ $permission->description }}</td>
							<!-- <td>
								<a href="{{ route('admin.permission.show',['permission' => $permission]) }}">Xem</a>
							</td> -->
							<td>
								<a href="{{ route('admin.permission.edit',['permission' => $permission]) }}">Sửa</a>
							</td>
							<td>													
								<a href="#" class="remove_link text-danger" data-toggle="modal" data-target="#destroy-permission" data-value="{{ route('admin.permission.destroy',['permission' => $permission]) }}">Xóa</a>
							</td>
						</tr>
						@endforeach
					</tbody>
				</table>
				<?php echo $permissions->render(); ?>
			</div>
		</div>
	</div>
</div>
<div id="destroy-permission" class="modal fade bs-example-modal-lg" tabindex="-1" permission="dialog" aria-hidden="true">
	<div class="modal-dialog modal-lg">
		<div class="modal-content">

			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span>
				</button>
				<h4 class="modal-title">Xóa quyền</h4>
			</div>
			<div class="modal-body">
				<p>Bạn có chắc chắn xóa quyền này chứ?</p>
			</div>
			<div class="modal-footer">
				<button id="close_button" type="button" class="btn btn-default" data-dismiss="modal">Close</button>
				<form id="destroy_form" style="display:inline;" action="" method="POST">
					{{ csrf_field() }}
					{{ method_field('DELETE') }}
					
					<button type="submit" class="btn btn-danger">Xóa</button>
				</form>				
			</div>

		</div>
	</div>
</div>

@endsection
@section('script')
<script>
	$(document).ready(function(){
		$(".remove_link").click(function(){
			$('#destroy_form').attr("action",$(this).attr("data-value"));
			
		});
		$("#close_button").click(function(){
			$('#destroy_form').attr("action",'');
		});
	});
</script>
@endsection

resources/views/admin/permission/install.blade.php
@extends('admin.layouts.apps')
@section('title')
Danh sách thành viên
@endsection
@section('main')
	<p>Sau đây là danh sách các quyền sẽ được cài đặt</p>
	<ul>
		@foreach($permissions as $permission)
			<li>
				{{ $permission }}
			</li>
		@endforeach
	</ul>
	<p class="text-danger">Việc cài đặt này có thể làm mất hết danh sách quyền!</p>
	<form action="{{route('admin.permission.install')}}" method="post">
		{{ csrf_field() }}
		<button type="submit">Cài đặt</button>		
	</form>
@endsection
@section('script')

@endsection

resources/views/admin/permission/show.blade.php
@extends('admin.layouts.apps')
@section('main')

<p>ID: {{ $permission->id }}</p>
<p>Name : {{ $permission->id }} </p>
<p>Tên hiển thị: {{ $permission->display_name}} </p>
<p>Miêu tả chi tiết: {{ $permission->description }} </p>

@endsection