routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route for authentication
Auth::routes();

// Route for frontend
Route::get('/','IndexController@index')->name('index');
Route::get('/gioi-thieu', 'IndexController@about')->name('gioi-thieu');
//Route::get('/khuyen-mai', 'IndexController@sale')->name('khuyen-mai');

Route::get('/dang-ky-kham', 'IndexController@registerMedicalApplication')->name('dang-ky-kham');
Route::post('/dang-ky-kham', 'IndexController@sendRegisterMedicalApplication');
Route::get('/dang-ky-thanh-vien', 'IndexController@registerMember')->name('dang-ky-thanh-vien');
Route::get('/dang-ky-thanh-vien', 'IndexController@registerMember')->name('dang-ky-thanh-vien');
Route::get('/thong-tin-benh-nhan', 'IndexController@personalInformation')->name('thong-tin-benh-nhan');

Route::get('/bac-sy/dang-ky', 'IndexController@registerDoctor')->name('dang-ky-bac-sy');
Route::post('/bac-sy/dang-ky', 'IndexController@sendRegisterDoctor');
Route::get('/bac-sy/quy-dinh', 'IndexController@doctorPolicy')->name('quy-dinh-bac-sy');
Route::get('/bac-sy/danh-sach', 'IndexController@doctorList')->name('danh-sach-bac-sy');
//Route::get('/bac-sy/thong-tin', 'IndexController@doctorInfomation')->name('thong-tin-bac-sy');

Route::get('/san-pham', 'IndexController@services')->name('san-pham');
Route::get('/dung-cu-y-te', 'IndexController@medicalInstruments')->name('dung-cu-y-te');
Route::get('/thuoc', 'IndexController@medical')->name('thuoc');

Route::get('/tin-tuc', 'IndexController@news')->name('tin-tuc');
Route::get('/cam-nang', 'IndexController@handBook')->name('hand-book');
Route::get('/tuyen-dung', 'IndexController@recruit')->name('recruit');
Route::get('/khuyen-mai', 'IndexController@sale')->name('sale');

Route::get('/lien-he', 'IndexController@contact')->name('contact');




// Route for backend
// All below route go with 'admin' prefix and need authentication
// All route name with add admin. prefix
Route::group([	'prefix' => 'admin',	'middleware' => 'auth', 'as' => 'admin.'	], function() {

	Route::get('/','AdminController@index')
	->name('index');

    Route::group([ 'middleware' => ['permission:manage-user']], function() {
		Route::resource('user',	'UserController');
    });

    Route::group(['middleware' => ['permission:manage-role']], function() {
        Route::resource('role', 'RoleController');
    });

    Route::group(['middleware' => ['role:admin']], function() {
        Route::get('permission/install','PermissionController@install')->name('permission.install');
        Route::post('permission/install','PermissionController@installPost')->name('permission.generate');
		Route::resource('permission',	'PermissionController');
    });

    Route::group(['middleware' => ['permission:manage-category']], function() {
        Route::resource('category', 'CategoryController');
    });

    Route::group(['middleware' => ['permission:manage-tag']], function() {
        Route::resource('tag', 'TagController');
    });

    Route::group(['middleware' => ['permission:manage-post']], function() {
        Route::resource('post', 'PostController');
    });

}); //End route group admin

Route::get('post/{slug}', 'IndexController@viewPost');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Zizaco\Entrust\Traits\EntrustUserTrait;

class User extends Authenticatable
{
    use Notifiable;
    use EntrustUserTrait;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'phone'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;
use App\Role;
use Redirect;
use App\Http\Requests\UserRequest;

class UserController extends Controller
{
    //Return index, show list of users
    //Method get
    public function index(){
        $roles = Role::all();
        $users = User::paginate(20);        
        return view('admin.user.index',compact('users','roles'));
    }

    //Show role details
    //Method get
    public function show($user){
        $user = User::findOrFail($user);
        return view('admin.user.show',compact('role'));
    }

    //Return create role page
    //Method get
    public function create(){
        $users = User::all();
        $roles = Role::all();
        return view('admin.user.create',compact('users','roles'));
    }

    //Store a role to database
    //Method post
    public function store(UserRequest $request){
        try {
            
            $user =  User::create([
            'name' => $request['name'],
            'email' => $request['email'],
            'password' => bcrypt($request['password']),
            ]);

            $roles = Role::all();
            foreach ($roles as $role) {
                echo $request->input($role->id).PHP_EOL;
                if($request->input($role->id)){
                   $user->attachRole($role);
                }
            }
            //dd($request->all());
            //return 0;


            \Session::flash('flash_message','Đã tạo người dùng '.$user->name .' thành công!');
            return redirect()->route('admin.user.index');
        } catch (\Illuminate\Database\QueryException $e) {
            if($e->errorInfo[1]==1062){
                return Redirect::back()->withErrors('Dữ liệu nhập trùng với dữ liệu trong cơ sở diệu');
            }
            return Redirect::back()->withErrors($e->errorInfo[2]);
        }

    }

    //Show role edit page
    //Method get
    public function edit($user){
        $user = User::findOrFail($user);
        $roles = Role::all();
        return view('admin.user.edit',compact('user','roles'));
    }

    //Update a role
    //Method put patch
    public function update($user, UserRequest $request){
        
        $user = User::findOrFail($user);
        $roles = Role::all();
        $user->roles()->sync([]); 
        foreach ($roles as $role) {
                //echo $request->input($role->id).PHP_EOL;
                if($request->input($role->id)){
                   $user->attachRole($role);
                }
            }
        if($request->has('password')){
            $user->password = bcrypt($request->input('password'));
        }
        //else return "Mật khẩu rỗng";
        $user->name = $request->input('name');
        $user->save();
        \Session::flash('flash_message','Đã sửa người dùng thành công!');       

        return Redirect::back();
    }
    
    //Remove a role
    //Method delete
    public function destroy($user){
        User::whereId($user)->delete();
        \Session::flash('flash_message','Đã xóa người dùng thành côngs!');
        return redirect()->route('admin.user.index');

    }
}

resources/views/admin/user/create.blade.php
@extends('admin.layouts.apps')
@section('title')
Thêm người dùng
@endsection
@section('main')

<div class="col-md-12 col-sm-12 col-xs-12">
    @if($errors->any())
    <div class="alert alert-danger alert-dismissible fade in" user="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span>
        </button>
        <strong>Lỗi!</strong>

        <ul>
            @foreach ($errors->all() as $message)
            <li>{{$message}}</li>
            @endforeach
        </ul>

    </div>
    @endif
    <div class="x_panel">
        <div class="x_title">
            <h2>Thêm người dùng</h2>

            <div class="clearfix"></div>
        </div>
        <div class="x_content">
            <br />
            <form action="{{ route('admin.user.store') }}" id="add_user" data-parsley-validate class="form-horizontal form-label-left" method="POST">
                {{ csrf_field() }}

                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">Tên người dùng <span class="required">*</span>
                    </label>
                    <div class="col-md-6 col-sm-9 col-xs-12">
                        <input name="name" type="text" required="required" class="form-control col-md-7 col-xs-12">
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">Email <span class="required">*</span>
                    </label>
                    <div class="col-md-6 col-sm-9 col-xs-12">
                        <input name="email" type="text" class="form-control col-md-7 col-xs-12" required="required">
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">Password <span class="required">*</span>
                    </label>
                    <div class="col-md-6 col-sm-9 col-xs-12">
                        <input name="password" type="password"  class="form-control col-md-7 col-xs-12" required="required">
                    </div>
                </div>

                <div class="form-group">

                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">Password Confirmation <span class="required">*</span>
                    </label>
                    <div class="col-md-6 col-sm-9 col-xs-12">
                        <input name="password_confirmation" type="password"  class="form-control col-md-7 col-xs-12" required="required">
                    </div>
                </div>

                <div class="form-group">
                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">Phân quyền</label>
                <div class="col-md-9 col-sm-9 col-xs-12">
                    @foreach($roles as $role)
                    <div class="checkbox">
                        <label>
                          <input type="checkbox" name="{{$role->id}}" value="{{$role->name}}" >
                          {{ $role->display_name?$role->display_name:$role->name }}
                        </label>
                      </div>
                      @endforeach
                </div>
                </div>

                <div class="ln_solid"></div>
                <div class="form-group">
                    <div class="col-md-6 col-sm-9 col-xs-12 col-md-offset-3 col-sm-offset-3">
                        <a href=".">
                            <button class="btn btn-default" type="button">Quay lại</button>
                        </a>
                        <button class="btn btn-default" type="reset">Reset</button>
                        <button type="submit" class="btn btn-success">Thêm</button>
                    </div>
                </div>

            </form>
        </div>
    </div>
</div>

@endsection
@section('script')
<!-- Parsley -->
<script src="{{ asset('backend/vendors/parsleyjs/dist/parsley.min.js') }}"></script>
@endsection

resources/views/admin/user/edit.blade.php
@extends('admin.layouts.apps')
@section('title')
Sửa thông tin người dùng
@endsection
@section('main')    

<div class="col-md-12 col-sm-12 col-xs-12">
    @if(Session::has('flash_message'))
        <div class="alert alert-success"><em> {!! session('flash_message') !!}</em></div>
    @endif
    @if($errors->any())
    <div class="alert alert-danger alert-dismissible fade in" user="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span>
        </button>
        <strong>Lỗi!</strong> 

        <ul>
            @foreach ($errors->all() as $message) 
            <li>{{$message}}</li>
            @endforeach
        </ul>

    </div>
    @endif
    <div class="x_panel">
        <div class="x_title">
            <h2>Sửa người dùng</h2>

            <div class="clearfix"></div>
        </div>
        <div class="x_content">
            <br />
            <form action="{{ route('admin.user.update',['user' => $user]) }}" id="add_user" data-parsley-validate class="form-horizontal form-label-left" method="POST">

                {{ csrf_field() }}
                {{ method_field('PATCH') }}

                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">Tên người dùng <span class="required">*</span>
                    </label>
                    <div class="col-md-6 col-sm-9 col-xs-12">
                        <input name="name" type="text" required="required" class="form-control col-md-7 col-xs-12" value="{{$user->name}}">
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name" >Email
                    </label>
                    <div class="col-md-6 col-sm-9 col-xs-12">
                        <input name="email" type="text" class="form-control col-md-7 col-xs-12" disabled value="{{$user->email}}">
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">Password
                    </label>
                    <div class="col-md-6 col-sm-9 col-xs-12">

                        <input name="password" type="password"  class="form-control col-md-7 col-xs-12" value="" placeholder="Password">
                    </div>
                </div>



                <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">Password
                    </label>
                    <div class="col-md-6 col-sm-9 col-xs-12">

                        <input name="password_confirmation" type="password"  class="form-control col-md-7 col-xs-12" value="" placeholder="Password confirm">

                    </div>
                </div>

                <div class="form-group">
                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">Phân quyền</label>
                <div class="col-md-9 col-sm-9 col-xs-12">
                    @foreach($roles as $role)
                    <div class="checkbox">
                        <label>
                          <input type="checkbox" name="{{$role->id}}" value="{{$role->name}}" 
                          {{ ($user->hasRole($role->name))?'checked':' ' }}>
                          {{ $role->display_name?$role->display_name:$role->name }}
                        </label>
                      </div>                                      
                      @endforeach
                </div>
                </div>

                <div class="ln_solid"></div>
                <div class="form-group">
                    <div class="col-md-6 col-sm-9 col-xs-12 col-md-offset-3 col-sm-offset-3">
                        <a href="..">
                            <button class="btn btn-default" type="button">Quay lại</button>
                        </a>
                        <button class="btn btn-default" type="reset">Reset</button>

                        <button type="submit" class="btn btn-success">Cập nhật</button>
                    </div>
                </div>

            </form>
        </div>
    </div>
</div>

@endsection
@section('script')
<!-- Parsley -->
<script src="{{ asset('backend/vendors/parsleyjs/dist/parsley.min.js') }}"></script>
@endsection

resources/views/admin/user/index.blade.php
@extends('admin.layouts.apps')
@section('title')
Danh sách thành viên
@endsection
@section('main')
<div class="col-md-12 col-sm-12 col-xs-12">

	@if(Session::has('flash_message'))
	<div class="alert alert-success"><em> {!! session('flash_message') !!}</em></div>
	@endif
	<div class="x_panel">
		<div class="x_title">
			<h2>Danh sách người dùng</h2>                    
			<div class="clearfix"></div>
		</div>

		<div class="x_content">
			<div class="table-responsive">
			<?php echo $users->render(); ?>
				<table class="table table-striped jambo_table bulk_action">
					<thead>
						<tr class="headings">
							<td>ID</td>
							<td>Tên</td>
							<td>Email</td>
							<td>Phân vai</td>
							<!-- <td>Xem</td> -->
							<td>Sửa</td>
							<td>Xóa</td>
						</tr>
					</thead>
					<tbody>
						@foreach($users as $user)
						<tr>
							<td>{{ $user->id }}</td>
							<td>{{ $user->name }}</td>
							<td>{{ $user->email }}</td>
							<td>
								@foreach($roles as $role)
									@if($user->hasRole($role->name))
										<a href="{{ route('admin.role.edit',['role' => $role]) }}" target="_blank">
											{{ $role->display_name?$role->display_name:$role->name }}
										</a>
										<br/>
									@endif
								@endforeach
							</td>
							<!-- <td>
								<a href="{{ route('admin.user.show',['user' => $user]) }}">Xem</a>
							</td> -->
							<td>
								<a href="{{ route('admin.user.edit',['user' => $user]) }}">Sửa</a>
							</td>
							<td>													
								<a href="#" class="remove_link text-danger" data-toggle="modal" data-target="#destroy-user" data-value="{{ route('admin.user.destroy',['user' => $user]) }}">Xóa</a>
							</td>
						</tr>
						@endforeach
					</tbody>
				</table>
				<?php echo $users->render(); ?>
			</div>
		</div>
	</div>
</div>
<div id="destroy-user" class="modal fade bs-example-modal-lg" tabindex="-1" user="dialog" aria-hidden="true">
	<div class="modal-dialog modal-lg">
		<div class="modal-content">

			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span>
				</button>
				<h4 class="modal-title">Xóa người dùng</h4>
			</div>
			<div class="modal-body">
				<p>Bạn có chắc chắn xóa người dùng này chứ?</p>
			</div>
			<div class="modal-footer">
				<button id="close_button" type="button" class="btn btn-default" data-dismiss="modal">Close</button>
				<form id="destroy_form" style="display:inline;" action="" method="POST">
					{{ csrf_field() }}
					{{ method_field('DELETE') }}
					
					<button type="submit" class="btn btn-danger">Xóa</button>
				</form>				
			</div>

		</div>
	</div>
</div>

@endsection
@section('script')
<script>
	$(document).ready(function(){
		$(".remove_link").click(function(){
			$('#destroy_form').attr("action",$(this).attr("data-value"));
			
		});
		$("#close_button").click(function(){
			$('#destroy_form').attr("action",'');
		});
	});
</script>
@endsection

resources/views/admin/user/show.blade.php
@extends('admin.layouts.apps')
@section('main')

<p>ID: {{ $role->id }}</p>
<p>Name : {{ $role->id }} </p>
<p>Tên hiển thị: {{ $role->display_name}} </p>
<p>Miêu tả chi tiết: {{ $role->description }} </p>

@endsection